### PR TITLE
Refactoring classes and properties - part 3

### PR DESCRIPTION
**Pull request by kmruehl**
This PR is a continuation of https://github.com/WEC-Sim/WEC-Sim/pull/803 and #822 

**Objectives:**
- clear and intuitive variable naming using camelCase
- consistent properties across classes, e.g. `pto.loc` versus `mooring.ref`
- convert properties for a single feature to property structures, e.g. `struct(body.morison)` 
- move properties to the appropriate class, e.g.  `simu.yaw` to `body.yaw`
- updating WEC-Sim library accordingly

**Wave Class**
- [x] `waves.etaImport` to `waves.waveImport` to `waves.elevationImport`
- [x]  `waves.spectrumDataFile` to `waves.waveSpectrumFile` to `waves.spectrumFile`
- [x] `waves.etaDataFile` to `waves.waveElevationFile`to `waves.elevationFile`
- [x] `waves.plotEta` to `waves.plotElevation`
- [x] `waves.waveDir` to `waves.waveDirection` to `waves.direction`
- [x] `waves.waveSpread` to `waves.spread`
- [x] `beta` to `theta` to match online documentation
- [x] `waves.deepWaterWave` to `waves.deepWater`
- [x] convert `waves.current` properties to structure, similar to morison element, 
  - `waves.currentOption` to `waves.current.option`
  - `waves.currentDepth` to `waves.current.depth`
  - `waves.currentDirection` to `waves.current.direction`
  - `waves.currentSpeed` to `waves.current.speed`
- [x] convert properties related to BEM data to `waves.bem` structure
  - `waves.numFreq` to `waves.freqNum` to `waves.bem.count`
  - `waves.freqDisc` to `waves.bem.option`
  - `waves.freqRange` to `wave.bem.range`
- [x] add checks for waveClass structures
- [x] convert `waves.marker` properties to structure
   - [x] `waves.markerLoc` to `waves.marker.loc` to `waves.marker.location`
   - [x] `waves.markerSize` to `waves.marker.size`
   - [x] `waves.markerStyle` to `waves.marker.style` 
   - [x] convert `waves.marker` properties to structure in Frames Library
- [x] `waves.T` to `waves.period`
- [x] `waves.H` to `waves.height` 

**Simulation Class**
- [x] `simu.writetxt` to `simu.writeText` to `simu.saveText`
- [x] `waves.waveStatisticsDataLoad` to `simu.mcrExcelFile`  (formerly Wave Class)
- [x] `simu.mcrCaseFile` to `simu.mcrMatFile`
- [x] `simu.dtME` to `simu.morisonDt`
- [x] `simu.CTTime` to `simu.cicTime`
- [x] `simu.dtCI` to `simu.cicDt`
- [x] `simu.CITime` to `simu.cicEndTime`
- [x] `simu.CIkt` to `simu.cicLength`
- [x] `simu.ssCalc` to `simu.stateSpace`
- [x] `simu.setupSimu` to `simu.simuSetup` to `simu.setup`
- [x] convert `simu.paraview` properties to structure, similar to morison element, note: test that sub-properties are tested 
    - `simu.dtParaview` to `simu.paraviewDt` to `simu.paraview.dt`
    - `simu.StartTimeParaview` to  `simu.paraviewStartTime` to  `simu.paraview.startTime`
    - `simu.EndTimeParaview` to `simu.paraviewEndTime` to `simu.paraview.endTime`
    - `simu.pathParaviewVideo` to `simu.paraviewDirectory` to `simu.paraview.path`
- [x] `simu.numWecBodies` to `simu.body.numHydroBodies`
- [x] `simu.pressureDis` to `simu.pressure`
- [x] `simu.simulationDate` to `simu.date`
- [x] add checks for simulationClass structures
- [x] `simu.adjMassWeightFun` to `simu.adjMassFactor`
- [x] `simu.autoRateTranBlk` to `simu.rateTransition`
- [x] `simu.zeroCrossCont` to `simu.zeroCross`
- [x] `simu.numIntMidTimeSteps` removed
- [x] `parallelComputing_dir` to `pctDir` **NOTE** this is not in the simulationClass, but maybe it should be

**Body Class**
- [x] `body.dof_start` to ``body.dofStart``
- [x] `body.dof_end` to ``body.dofEnd``
- [x] `body.dof_gbm` to ``body.dofGBM`` to `body.gbmDOF`
- [x] `body.nlHydro` to ``body.nonlinearHydro``
- [x] `body.lenJ` to ``body.dofCoupled``
- [x] `body.meanDriftForce` to ``body.meanDrift``
- [x] `body.bodyparaview` to ``body.paraviewBody`` to ``body.paraview``
- [x] `body.flexHydroBody` to ``body.flexBody`` to ``body.flex``
- [x] `body.nhBody` to ``body.nonHydroBody`` to ``body.nonHydro``
- [x] `body.hydroDataBodyNum` to ``body.hydroBodyTotal`` to `body.hydroTotal` **NOTE** Do we even use this?
- [x] `body.viscDrag` to `body.viscousDrag` to `body.quadDrag`
- [x] `body.userDefinedExcIRF` to `body.excitationIRF`
- [x] add checks for bodyClass structures
- [x] move `simu.yaw` and `simu.yawThresh` to bodyClass 
   - [x] `simu.yaw` to `body.yaw.option`
   - [x] `simu.yawThres` to `body.yaw.threshold`
- [x] `body.bodyNumber` to `body.number`
- [x] `body.bodyTotal` to `body.total`
- [x] `body.bodyGeometry` to `body.geometry`
from @nathanmtom 
- [x] `quadDrag.Drag` to `quadDrag.drag`
- [x] `morisonElement.characteristicArea` to `morisonElement.area`
- [x] `quadDrag.characteristicArea` to `quadDrag.area`
- [x] `dispVol` to `displacedVolume` to `volume`
- [x] `body.initDisp.initLinDisp` to `body.initDisp.initLinearDisp` to `body.initial.displacement`
- [x] `body.initDisp.initAngularDispAngle` to  `body.initial.angle`
- [x] `body.initDisp.initAngularDispAxis` to  `body.initial.axis`
- [x] `cg` to `centerGravity`
- [x] `cb` to `centerBuoyancy`
- [ ] `momOfInertia` to `intertia`

**Cable Class**
- [x] `cable.c` to `cable.damping`
- [x] `cable.k` to `cable.stiffness`
- [x] `cable.viscDrag` to `cable.viscousDrag` to `cable.quadDrag` 
- [x] `cable.cableNum` to `cable.number`
- [x] `cable.loc` to `cable.location`
from @nathanmtom 
- [x] `cable.dispVol` to `cable.displacedVolume` to `cable.volume`
- [x] `cable.quadDrag.characteristicArea` to `quadDrag.area`
- [x] `cable.quadDrag.Drag` to `quadDrag.drag`
- [x] `cable.initDisp.initLinDisp` to `cable.initDisp.initLinearDisp` to `cable.initial.displacement`
- [x] `cable.initDisp.initAngularDispAngle` to  `cable.initial.angle`
- [x] `cable.initDisp.initAngularDispAxis` to  `cable.initial.axis`
- [x] `cable.L0` to `cable.unstretchedLength` tp `cable.length`
- [x] `cable.bodyMass` to `cable.mass`
- [x] `cable.bodyInertia` to `cable.momOfInertia` to `cable.intertia`
- [x] convert to `cable.base` and `cable.follower` structure
   - [x] `cable.cb1` to `cable.centerBuoyancyBase` to `cable.baseCb` to `cable.base.centerBuoyancy`
   - [x] `cable.cg1` to `cable.centerGravityBase` to `cable.baseCg` to `cable.base.centerGravity`
   - [x] `cable.rotloc1` to `cable.rotationLocation1` to `cable.baseLocation` to to `cable.base.location`
   - [x] `cable.baseConnectionName` to `cable.base.name`
   - [x] `cable.cb2` to `cable.centerBuoyancyFollower` to `cable.followerCb` to `cable.follower.centerBuoyancy`
   - [x] `cable.cg2` to `cable.centerGravityFollower` to `cable.followerCg` to `cable.follower.centerGravity`
   - [x] `cable.rotloc2` to `cable.rotationLocation2` to `cable.followerLocation` to `cable.follower.location`
   - [x] `cable.followerConnectionName` to `cable.follower.name`

**Constraint Class**
- [x] `constraint.loc` to `constraint.location`
- [x] `constraint.constraintNum` to `constraint.number`
from @nathanmtom 
- [x] `constraint.initDisp.initLinDisp` to `constraint.initDisp.initLinearDisp` to `constraint..initial.displacement`

**PTO Class**
- [x] `pto.loc` to `pto.location`
- [x] `pto.c` to `pto.damping`
- [x] `pto.k` to `pto.stiffness`
- [x] `pto.ptoNum` to `pto.number`
from @nathanmtom 
- [x] `pto.initDisp.initLinDisp` to `pto.initDisp.initLinearDisp` to `pto.initial.displacement`

**Mooring Class**
- [x] `mooring.ref` to `mooring.loc` to `mooring.location`
- [x] `mooring.loc` to `mooring.orientation` (internal)
- [x] `mooring.mooringNum` to `mooring.number`
from @nathanmtom 
- [x] `mooring.initDisp.initLinDisp` to `mooring.initDisp.initLinearDisp` to `mooring.initial.displacement`
- [x] `mooring.initDisp.initAngularDispAngle` to  `mooring.initial.angle`
- [x] `mooring.initDisp.initAngularDispAxis` to  `mooring.initial.axis`

**Doc**
- [ ] add dev documentation for style guide, look into naming convention, e.g. pep 8

**Notes**
- [x] Are the property structure fields checked? No, properties are automatically checked, but not the structure fields. For example there's an error if `waves.bems` is specified in the input file, but not for `waves.bem.options`. This can be addressed by adding some additional checks to the `checkinputs` method of each class with a structure.
- [x] resolve `TestPassiveYawRegression` test failure
- [ ] how does b2b impact migration of passive yaw to bodyClass?
- [ ] resolve `wecSimPCT` issue
- [ ] move `pctDir` to simulationClass?

### CODE REVIEW

**Comment by kmruehl** [comment]
Review from @nathanmtom 

Working review comments: 

**Body Class**
- [x] `quadDrag.Drag` to `quadDrag.drag`
- [x] `morisonElement.characteristicArea` to `morisonElement.area`
- [x] `quadDrag.characteristicArea` to `quadDrag.area`
- [ ] `cg` to `centerGravity`
- [ ] `cb` to `centerBuoyancy`
- [ ] `dispVol` to `displacedVolume` to `volume`
(we agreed to have acronyms, i.e. IRF, but certain words are fully written out and not so this would be for perceived consistency.)
- [x]  In the original comment of this PR there is `body.dof_gbm` to `body.dofGBM` but in the `simulationClass` it appears to be `gbmDOF` no issue with this labeling, but just confirming intent.)
**kmruehl: my mistake, it should be `gbmDOF`, I'll update this**
- [ ] `body.initDisp.initLinDisp` to `body.initDisp.initLinearDisp`

**Wave Class**
- [ ] `waves.T` to `waves.period` (another case where if we are consistent with using full names than assumed variables we should change; however, I'd say this is pretty standard in our industry and do not think we have had any confusion here.)
- [ ] `waves.H` to `waves.height` (another case where if we are consistent with using full names than assumed variables we should change; however, I'd say this is pretty standard in our industry and do not think we have had any confusion here.)

**Simulation Class**
- [ ] `waves.writeText` seems to have been removed, just confirming intention here.
**kmruehl: do you mean responseClass.writeText?**

**Cable Class**
- [ ] `cable.L0` to `cable.unstretchedLength`
- [ ] Clarify that `linearDamping` and `quadDamping` in the cable class is related to the global motion of the cable, not associated with extension of the cable?
- [ ] `cable.cb1` to `cable.centerBuoyancyBase`
- [ ] `cable.cg1` to `cable.centerGravityBase`
- [ ] `cable.cb2` to `cable.centerBuoyancyFollower`
- [ ] `cable.cg2` to `cable.centerGravityFollower`
- [ ] `cable.dispVol` to `cable.displacedVolume` to `dispVol`
- [x] `cable.quadDrag.characteristicArea` to `quadDrag.area`
- [x] `cable.quadDrag.Drag` to `quadDrag.drag`
- [ ] `cable.initDisp.initLinDisp` to `cable.initDisp.initLinearDisp`
- [ ] `cable.rotloc1` to `cable.rotationLocation1` (Dom, am I interpreting the variable correctly?)
- [ ] `cable.rotloc2` to `cable.rotationLocation2` (Dom, am I interpreting the variable correctly?)

**Constraint Class**
- [ ] `constraint.initDisp.initLinDisp` to `constraint.initDisp.initLinearDisp`

**PTO Class**
- [ ] `pto.initDisp.initLinDisp` to `pto.initDisp.initLinearDisp`

**Mooring Class**
- [ ] `mooring.initDisp.initLinDisp` to `mooring.initDisp.initLinearDisp`

**Other Comments**
- Side comment here, but outside of it being difficult to maintain, it does seem like having a list of all variables in a table and every location they are used would be valuable to make similar changes in the future. Also, this allows to double check if a variable is actually used or not. I would appreciate some thoughts on if the team can think of a good method for this.

**Comment by kmruehl** [comment]
@H0R5E do you know why the tests stopped running on this PR?

**Comment by kmruehl** [comment]
> @kmruehl, no, I don't know why. V strange.

indeed...

**Comment by H0R5E** [comment]
Actions are [degraded](https://www.githubstatus.com/). You'll need to wait for a fix.

**Comment by akeeste** [comment]
A few more comments on our refactoring:

I notice that the only places we use short industry-standard variables instead of words for naming is the internal part (but public accessible) part of the wave class. Seems feasible to update these last few before v5.0

``pctDir`` is appended onto ``simu.caseDir`` when wecSimPCT is used, so we probably don't have to save it as a separate variable

on setAccess and getAccess:
- the ``number`` property is almost always public-public because it's set in ``initializeWecSim`` but it should not be set by users. We could create simple ``setNumber()`` methods so that they can be private-public
- ``mooring.orientation`` is not used anywhere. It's not used in the same way as the other classes
- ``pto, constraint, mooring`` are otherwise straightforward in this regard
- ``response`` no changes needed here
- move ``waves.type`` to private-public. ``typeNum`` is set privately and only in the class constructor so ``type`` must be set through the constructor as well
- ``body.geometry, body.h5File`` to private-public and probably need to redo the docstring so that the API pulls the full description (like ``body.morisonElement``
- ``body.dofCoupled, body.total`` to private-public and set in a method like ``checkInputs``
- ``body.hydroTotal`` not used
- ``body.massCalcMethod`` to private-public and should likely be removed from ``initializeWecSim`` line 149, I dont' see why this  parameter should be set there
- ``simu.cicTime, simu.cicLength, simu.caseFile, simu.date, simu.gitCommit, simu.maxIt, simu.outputDir, simu.wsVersion`` aren't used outside of the simulationClass, move to private-public
- ``simu.inputFile, simu.logFile`` aren't used
- ``simu.numX`` used in initializeWecSim but could be moved to a ``setNum`` method and be private-public

**Comment by kmruehl** [comment]
@akeeste and @nathanmtom This branch is currently stable and passing all tests so I'm going to merge this PR and open a new one to address the remaining comments.

**Pull request merged**
