### PR TITLE
Dev: adding ampSpectraForWS function

### PR DESCRIPTION
**Pull request by dforbush2**
This is related to issue #873 . While we recommend spectrumImport instead of elevationImport as a more robust solution method for user-defined wave time series, we previously have not provided a tool to convert the elevationImport.mat --> spectrumImport.mat. The addition of this single function fixes that.

### CODE REVIEW

**Comment by akeeste** [comment]
@dforbush2 I tested the function with a sample irregular wave. It works well and gives very similar results to MHKiT. I don't have any issue with the function, but prefer to encourage users to use MHKiT for this purpose. MHKiT already has tests and documentation built in as well. If users have MHKiT-MATLAB installed, it would be straightforward to use their ``elevation_spectrum`` function.


pr907 amp spectrum

**Review by akeeste — CHANGES_REQUESTED** [review]
@dforbush2 

Per my previous comments, I made a PR into your dev branch with a few updates, including:
- remove WEC-Sim ``ampSpectraForWS`` funtion
- add to your documentation update pointing users to MHKiT
- remove changes to ``source/functions/simulink/model/nonLinearBuoyancy.m`` which i believe is meant for your other PR #910

After these changes we can merge this PR

**Comment by akeeste** [comment]
TODO for Adam:
- [ ] also compare complex amplitude of the spectra and compare how the timeseries elevation of each spectra comes out in WEC-Sim

**Comment by kmruehl** [comment]
@dforbush2 @akeeste is this ready for a merge?

**Pull request merged**
