### PR TITLE
Bug fixes for WEC-Sim GUI and Run From Simulink features

### PR DESCRIPTION
**Pull request by akeeste**
This PR fixes two bugs brought up in #1184:
- [x] ``loadInputFileCallback.m`` broke when the top level of a model had non-WEC-Sim library blocks
- [x] ``writeInputFromBlocks`` was not writing strings to the input file robustly. The command to write a new input file would break when paths contained "\U" or other special character combos, which was typical when a user selected a file of some kind (e.g. body(1).geometryFile = "C:\Users\name\...\geometry\file.stl")

### CODE REVIEW

**Comment by akeeste** [comment]
``writeInputFromBlocks`` has many lines changed because I updated how the ``writeLineFromVar`` function works. This changed each call to ``writeLineFromVar`` within ``writeInputFromBlocks``. Each line of the input file must be written using the ``'%s'`` notation in fprintf so that strings are written correctly and the line break can still be added.

**Comment by akeeste** [comment]
@kmruehl There was another problem identified with my solution in #1184 . I'll work to make this bugfix more robust this week.

**Comment by akeeste** [comment]
@kmruehl This is now ready for review

**Comment by kmruehl** [comment]
@MShabara  and @jleonqu  this is ready for review

**Comment by jleonqu** [comment]
@akeeste I was able to test this PR and it works well on my end. I tested this PR in Matlab 2022b and Matlab 2023b.
I tested this PR in a similar way than you in issue #1184

**Review by jleonqu — APPROVED** [review]
@akeeste  I was able to test this PR and it works well on my end. I tested this PR in Matlab 2022b and Matlab 2023b.
I tested this PR in a similar way than you in issue #1184

**Comment by MShabara** [comment]
@akeeste I tested the modifications using MATLAB 2023b and the model works perfectly, 
good job!

**Pull request merged**
