### PR TITLE
Bug fix: responseClass reading the MoorDyn Lines.out file too early, resolves #811

### LINKED ISSUE #811: [BUG]Paraview_Visualization\RM3_MoorDyn_Viz
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**

I encountered the same error in #674, then I tried to download the code in #682 , but the problem was still there 

**WEC-Sim file(s)**
WEC-Sim_Applications-master\WEC-Sim_Applications-master\Paraview_Visualization\RM3_MoorDyn_Viz

**To Reproduce**
Install the latest version of MoorDyn for WEC-Sim at: https://github.com/WEC-Sim/MoorDyn. Run BEMIO.
Run the applications case: Paraview_Visualization\RM3_MoorDyn_Viz
See error:

_State method of running WEC-Sim (command line)_

**Expected behavior**
I expect the case to run as is without issue

**Screenshots**

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 10]
 - [MATLAB/Simulink] [ 2020b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v4.4]

**Additional context**
_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by akeeste**
This PR fixes the issue described in #811 and #674. The problem is that the WEC-Sim post-processing is being called before the MoorDyn ``Lines`` library closing function is being called. This updates the stop and close callbacks of the MoorDyn block, and adds a check to ``postProcess`` to ensure that MoorDyn is closed before the Lines.out file is read.

Adam

### CODE REVIEW

**Comment by akeeste** [comment]
@H0R5E I tried a similar loop to give MoorDyn time to finish writing output, but without success. I found that this is really a WEC-Sim order of operations issue, rather than a WEC-Sim/MoorDyn racing issue. No matter how much time is given, the Lines.out file is not complete until WEC-Sim calls the MoorDyn function ``LinesClose``.

This started occurring in the last couple of releases because we moved the WEC-Sim post-processing ``stopWecSim`` to be a stop function callback of the Frames blocks. These commands to close MoorDyn are in the MoorDyn block stop function callback.

Previously our post-processing order of operations was something like:
- Run Simulink
- MoorDyn callback when Simulink stops
    -  ``calllib('Lines','LinesClose');``
- ``stopWecSim``
    - ``output.loadMoorDyn()``

But right now our post-processing order of operations is:
- Run Simulink
- Frames callback when Simulink stops
    - ``stopWecSim``
        - ``output.loadMoorDyn()``
- MoorDyn callback when Simulink stops
    -  ``calllib('Lines','LinesClose');``

So our main post-processing is running before we actually close MoorDyn, which completes the Lines.out files. I had moved ``stopWecSim`` into the ``wecSim`` script to better debug and realized that this actually prevented the issue from occurring. I updated MoorDyn callbacks to be:
    if libisloaded('Lines')
        calllib('Lines','LinesClose');
        unloadlibrary Lines;
    end

This way MoorDyn will always close properly if Simulink crashes or stop unexpectedly, but it will not try to use the DLL if ``stopWecSim`` has already been run.

Adam

**Comment by H0R5E** [comment]
OK, Adam, makes sense. I am curious as to why the order of post-processing is as it is - would it not be sensible to post-process in the last step? Also, is there any way to build a test to catch this if it happens again?

**Comment by akeeste** [comment]
@H0R5E I agree, it would be better to run ``stopWecSim`` as our last step. We originally moved this to the Frames callback to make it easier for users to run From Simulink. However since this is a block-level callback and not a model level callback, we don't have control over when it is run. I believe the block callbacks are run in alphabetical order by block name, so the Global Reference Frame is running before MoorDyn. 

@kmruehl I think this should come into our larger discussion on the utility vs maintenance of Run From Simulink

And on the test -- hopefully one of our MoorDyn application tests can catch this. I'll think on this

**Comment by kmruehl** [comment]
Is this PR ready for a merge? I think we have a similar issue going on with wecSimPCT https://github.com/WEC-Sim/WEC-Sim/issues/782

**Comment by akeeste** [comment]
@H0R5E are there any other changes you recommend here before we merge?

**Comment by H0R5E** [comment]
No @akeeste, go ahead.

**Comment by kmruehl** [comment]
@akeeste I'm going to go ahead and merge this, but we need to put it in dev too. Can you make the same revisions on https://github.com/WEC-Sim/WEC-Sim/pull/822? Thank you!

**Pull request merged**
