### PR TITLE
update body library block mask to address #1346 on dev branch

### PR DESCRIPTION
**Pull request by dforbush2**
This is the equivalent of PR #1347 but made to the development branch. Credit to @hachikoi1 for finding the bug.

### CODE REVIEW

**Comment by kmruehl** [comment]
Thank you @dforbush2

**Comment by dforbush2** [comment]
@akeeste please ensure the GUI h5 button callback is functioning as intended: I believe this already existed on dev branch but difficult to confirm against #1347

**Comment by akeeste** [comment]
I'll review this next week and may supercede it with a likely library fix needed in #1351

**Comment by dforbush2** [comment]
This PR now also adds hydro.gbm field creation as appropriate to readCapytaine. Revert commit 0abf01c to remove this if desired.

This makes gbm modes specified in capytaine run out-of-the-box in wecSim, parallel functionality to what exists in readWAMIT with the following exception:

Capytaine does not at this time allow the specification of non-zero mechanical inertia, mechanical damping, and mechanical stiffness in the BEM run itself. These fields, (hydro.gbm(:,:,[1:3], respectively) are all set to zero, but the last element hydro.gbm(:,:,4) is the hydrostatic stiffness which is calculated. This may need to be changed in a future capytaine update, and throws a warning for now.

**Comment by akeeste** [comment]
@dforbush2 I pull the most recent versions of dev and main into this branch and double checked the library for 4 recent bugfixes :
- addition of h5FileButtonCallback in the flex body mask from #1353
- update variable hydro From flag in CIC and constant coefficients calculation in the flex body mask from #1353
- update variable hydro From flag in CIC and constant coefficients calculation in the Rigid Body/hydro body mask from #1353
- make the second-order excitation force block a non-atomic subsystem from #1351

The tests passed again so I'll merge this

**Pull request merged**
