### PR TITLE
MOST Capabilities

### PR DESCRIPTION
**Pull request by akeeste**
This is the major pull request coupling WEC-Sim and the MOST software package. Active developments before this PR is merged will go into the MOREnergyLab/WEC-Sim repository.

TODO list before release:
- [x] mooring lookup table block MOREnergylab/WEC-Sim#2
- [x] refactoring of windClass MOREnergylab/WEC-Sim#3
- [x] refactoring of windTurbineClass MOREnergylab/WEC-Sim#5
- [x] Create a set of MOST IO functions for a new pre-processing stage MOREnergylab/WEC-Sim#5
- [ ] Expand and include documentation on MOST and its use MOREnergylab/WEC-Sim#1 (may be others)
- [x] Review by the larger WEC-Sim team @jtgrasb

TODO items outside of GitHub:
- [x] Draft publication statement on the new WEC-Sim+MOST capabilities
- [ ] Ask MOST to track GitHub traffic (users, PRs, downloads, forks, stars, etc)
- [ ] Set-up Google Analytics report specifically on the MOST subset of the documentation

### CODE REVIEW

**Comment by akeeste** [comment]
@jtgrasb Do you have time to review the MOST implementation in the next couple of weeks? It would be great to get a second WEC-Sim reviewer here since it's such a big addition. I've done a lot of refactoring to standardize with WEC-Sim's conventions, but any other feedback on improved or faster implementation would be welcome.

They're not requirements before the next release, but it would also be great to add:
- [ ] parameter validation for the ``windClass`` and ``windTurbineClass` 
- [ ] visualization of the wind turbine in ``responseClass.saveViz``

**Comment by jtgrasb** [comment]
@akeeste Yeah, I should have some time in the next couple weeks. Look forward to checking it out!

**Comment by akeeste** [comment]
@jtgrasb Great, thank you! My WEC-Sim/WEC-Sim_Applications#36 has a working WEC-Sim+MOST case. It's currently tracking my ``most`` branch, which should be pulled into MOREnergyLab ``dev`` soon. The .h5 file is not included yet, but can be copied from [here](https://github.com/WEC-Sim/MOST_simscape/blob/master/hydroData/Volturn15MW_wamit.h5) for local runs.

**Comment by jtgrasb** [comment]
@akeeste I noticed there's still a lot going on with this PR in terms of new commits. Should I wait until some of those changes are complete to review this?

**Comment by akeeste** [comment]
@jtgrasb Since my latest PR was merged, it looks like the new commits are primarily documentation focused. So I don't think we need to wait. I'll follow-up at our Wednesday meeting

**Comment by jtgrasb** [comment]
Thank you for all your hard work @MOREnergylab! This PR and the documentation is very well done. I will work on getting the mooring library block conflict resolved and merging the PR.

**Pull request closed without merging**
