### PR TITLE
Run from sim updates

### PR DESCRIPTION
**Pull request by akeeste**
This PR clean up various Run From Simulink items. It is composed of all changes that were split from PR #728. No functional changes are made, only refactoring of the mask callbacks for clarity.

### CODE REVIEW

**Comment by akeeste** [comment]
I have pulled the most recent version of dev into this branch. The library update renames three mask parameters for the Run From Simulink functionality. For all blocks, these parameters are renamed in the following manner:
``WECSim_Lib_Body_Elements/Rigid Body/Mask Editor/Parameters & Dialog/CusInFile`` --> ``InputFileGroup``
``WECSim_Lib_Body_Elements/Rigid Body/Mask Editor/Parameters & Dialog/ParameterGroupVar`` --> ``CustomParameterGroup``
``WECSim_Lib_Body_Elements/Rigid Body/Mask Editor/Parameters & Dialog/ParamInput`` --> ``InputMethod``

This should make the Run From Simulink callbacks more clear to read and understand. Also, I moved the button to load parameters from an input file to a mask, into the "custom parameter" section of the Global Reference Frame mask since that is where it is actually used:
image

**Comment by kmruehl** [comment]
@akeeste this looks good to me. Thanks for cleaning up the run from Simulink functions. Are there any doc updates you'd like to make based on this PR, to the http://wec-sim.github.io/WEC-Sim/dev/developer/library.html#library-development section?

**Review by kmruehl — APPROVED** [review]

**Comment by akeeste** [comment]
@kmruehl I double checked the docs. I updated a couple images since the mask variable names change slightly, but otherwise the content in that section is not affected.

**Comment by kmruehl** [comment]
@akeeste you may want to delete this branch

**Pull request merged**
