### PR TITLE
fix to #1217, nonlinFK and body block changed

### PR DESCRIPTION
**Pull request by dforbush2**
Credit to @guangyaow on catching the error and proposing the fix. 
This fix makes nonlinear froude krylov work for **plane waves** with **non-zero** directions. If the waves are not plane waves (e.g, there are a sum of wave trains from different directions) this will not work correctly. Capabilities will be expanded in a future PR.

Hotfix merge into master is intentional

### CODE REVIEW

**Comment by dforbush2** [comment]
This is ready to go. To avoid confusion for the reviewer note that:
1) elv input is from waveElevation and is a vector that is equal in length to the center(:,3) from the STL file. This updates every time step. This elv already accounts for a non-zero wave direction to solve for wave elevation at [center(:,1), center(:,2)]. So Z= center(:,3)- elv accurately reflects the difference in height between the body panel in Z and the free surface at that same (x,y) point. 
2) For regular waves it is possible to use elv as the input since it is monochromatic. For irregular waves, the portion of the hydrostatic pressure equation for elevation must be recalculated because the check for deep water conditions happens every frequency. Recall that elv is elevation due to all frequency components at the points (center(:,1), center(:,2)): hence although it is a bit redundant to repeat this calculation here it is necessary. 
3) The whole nonFKForce only works with planar waves. UserDefinedEta and the multiple wave train feature added recently is the only way currently that a user could input non-planar waves. Please update documentation related to this latter feature to indicate that non-linear forcing will not work

**Comment by guangyaow** [comment]
Hello, thanks so much for your response and clarification. If I want to use
UserDefinedEta and the multiple wave train feature (without considering the
nonlinear FK force), I need to define the waveclass as " waves = waveClass(
'elevationImport');", is my understanding correct? In addition, may I ask
what's the standard format for waves.elevationFile ='<elevationFile>.mat'
(how the elevation, which is a function of (x,y) and time. should be
stored)? Thanks.

Best,
Guangyao

**Comment by salhus** [comment]
Hi @guangyaow,

Yes, you are right.
For a template for the .mat file please refer to the examples and you would find .mat files for an elevation import, and a spectra import.

Cheers,
sal

**Comment by akeeste** [comment]
@salhus @dforbush2 Was there any change to the mask in this PR? I'm having issues merging updates into my variableHydro branch that I believe are ultimately coming from this PR into master.

Also *please* only squash and merge PRs into master/main/dev. The commit history on main is pretty messy now.

**Comment by dforbush2** [comment]
To my knowledge there is not a mask change but there is a change to the noted library block to pull in wave direction to the function. This MAY have resulted in a subsequent mask change when multiple wave trains I.e. multiple possible wave directions were added, but I don’t think that had to happen here.

**Comment by akeeste** [comment]
Thanks @dforbush2. I'll keep digging around for the issue on #1248

**Comment by akeeste** [comment]
Made some progress--my issue on #1248 was coming from a mask and Run From Simulink + WEC-Sim GUI which is hard to track, but is unrelated to anything done here.

**Pull request merged**
