### PR TITLE
Aqwa-phase-bug-resolved

### PR DESCRIPTION
**Pull request by salhus**
Added a line to add a phase offset to the phase data extracted from aqwa to account for the different sign conventions used.

Thus follows from #846

### CODE REVIEW

**Comment by kmruehl** [comment]
Thanks @salhus !

**Comment by tuisong1106** [comment]
Dear Salhus, the phase of excitation force read by this program is not consistent with the value in LIS file. Could you please help test whether the program needs to be improved? Thank you.

**Comment by salhus** [comment]
@tuisong1106 
Could you please share some examples, with if possible the time histories?
That will help me understand the potential issue.

**Comment by tuisong1106** [comment]
> @tuisong1106 您能否分享一些例子，如果可能的话，包括时间历史？ 这将帮助我理解潜在的问题。

I used AQWA to calculate the interaction between the two cylinders, and the reading program found that the excitation force was not matched, and the additional mass and damping coefficient were opposite in the upper right corner (the influence of 1 on 2) and the lower left corner (the influence of 2 on 1).

**Comment by tuisong1106** [comment]
> @tuisong1106 Could you please share some examples, with if possible the time histories? That will help me understand the potential issue.

I used AQWA to calculate the interaction between two cylinders, and the reading program found that the excitation force was not matched, and the added mass and radiation Damping were opposite in the upper right corner (the influence of 1 on 2) and the lower left corner (the influence of 2 on 1).

**Comment by salhus** [comment]
@tuisong1106 
Thanks for describing the issue.
However, it will help me understand if you can share the actual files .
The hydrodynamic couplings are typically symmetric matrices so I am not sure I followed what opposite implies.


Cheers,
Sal

**Comment by kmruehl** [comment]
Thanks @salhus

**Pull request merged**
