### PR TITLE
Fixing an inconsistent sign in the 'Electric Generator Equivalent Circuit' block in PTO-Sim

### PR DESCRIPTION
**Pull request by jleonqu**
An issue regarding the power calculated with the RM3 example using PTO-Sim was reported in #1218 

There are two inconsistent signs in the 'Electric Generator Equivalent Circuit'. The first inconsistent sign is in the voltage equation of the equivalent circuit. The correct equation for the voltage in the circuit is:

$` e - L_a \frac{di}{dt} - R_ai-R_{load}i = 0 `$
$` e = k_e \omega  `$

For the dynamic equation in the shaft, the torque input should be considered as a positive input, which is accelerating the motor shaft, and the electric torque should be negative because it is used to generate the electric power and it is decelerating the electric motor shaft. The correct dynamic equation is:

$` J_{EM} \ddot{\theta} = T_L - b_{shaft}\dot{\theta}-k_t i `$

This PR fix the signs in the 'Electric Generator Equivalent Circuit' block.

### CODE REVIEW

**Comment by dforbush2** [comment]
The signs seem to agree now and the dynamics make sense. One problem here is that it is assumed that Rload can go negative: this amounts to current injection (i.e., reactive power), and can be a bit misleading represented in this way. Recommend eventually revising to a command current at the inverter. 

Ready to merge.

**Comment by kmruehl** [comment]
@jleonqu should this go in dev or master?

**Comment by kmruehl** [comment]
@dforbush2  we usually recommend bugfix PRs into main (formerly master), and then we pull main into dev. That ensures that all bug fixes get propagated into both branches. @jleonqu can you update this PR to go into main, and then once merged we'll pull it into dev.

**Comment by jleonqu** [comment]
Done. I've changed the PR to 'main' and I've solved the conflicts. It is ready to merge

**Comment by kmruehl** [comment]
Thanks @jleonqu

**Comment by akeeste** [comment]
@jleonqu when this PR was changed from dev into main, did you rebase it to be based on the main branch? It looks like there are 185 files changed, and that all of dev was pulled into main, not just this fix

**Comment by akeeste** [comment]
This PR was force overwritten to remove the commit that included items from dev. See new PR

**Pull request merged**
