### PR TITLE
Refactoring classes and properties - part 2

### PR DESCRIPTION
**Pull request by kmruehl**
This PR is a continuation of https://github.com/WEC-Sim/WEC-Sim/pull/803. Refactoring WEC-Sim Classes and Properties based on [project board card](https://github.com/WEC-Sim/WEC-Sim/projects/58#card-64210391) and discussions with the WEC-Sim team. 

**Objectives:**
- clear and intuitive variable naming using camelCase
- consistent properties across classes, e.g. `pto.loc` versus `mooring.ref`
- convert properties for a single feature to property structures, e.g. `struct(body.morison)` 
- move properties to the appropriate class, e.g.  `simu.yaw` to `body.yaw`
- updating WEC-Sim library accordingly

**Wave Class**
- [x] `waves.etaImport` to `waves.waveImport` to `waves.elevationImport`
- [x]  `waves.spectrumDataFile` to `waves.waveSpectrumFile` to `waves.spectrumFile`
- [x] `waves.etaDataFile` to `waves.waveElevationFile`to `waves.elevationFile`
- [x] `waves.plotEta` to `waves.plotElevation`
- [x] `waves.waveDir` to `waves.waveDirection` to `waves.direction`
- [x] `waves.waveSpread` to `waves.spread`
- [x] `beta` to `theta` to match online documentation
- [x] `waves.deepWaterWave` to `waves.deepWater`
- [x] convert `waves.current` properties to structure, similar to morison element, 
  - `waves.currentOption` to `waves.current.option`
  - `waves.currentDepth` to `waves.current.depth`
  - `waves.currentDirection` to `waves.current.direction`
  - `waves.currentSpeed` to `waves.current.speed`
- [x] convert properties related to BEM data to `waves.bem` structure
  - `waves.numFreq` to `waves.freqNum` to `waves.bem.count`
  - `waves.freqDisc` to `waves.bem.option`
  - `waves.freqRange` to `wave.bem.range`
- [x] add checks for waveClass structures
- [x] convert `waves.marker` properties to structure
   - [x] `waves.markerLoc` to `waves.marker.loc` to `waves.marker.location`
   - [x] `waves.markerSize` to `waves.marker.size`
   - [x] `waves.markerStyle` to `waves.marker.style` 
   - [x] convert `waves.marker` properties to structure in Frames Library

**Simulation Class**
- [x] `simu.writetxt` to `simu.writeText`
- [x] `waves.waveStatisticsDataLoad` to `simu.mcrExcelFile`  (formerly Wave Class)
- [x] `simu.mcrCaseFile` to `simu.mcrMatFile`
- [x] `simu.dtME` to `simu.morisonDt`
- [x] `simu.CTTime` to `simu.cicTime`
- [x] `simu.dtCI` to `simu.cicDt`
- [x] `simu.CITime` to `simu.cicEndTime`
- [x] `simu.CIkt` to `simu.cicLength`
- [x] `simu.ssCalc` to `simu.stateSpace`
- [x] `simu.setupSimu` to `simu.simuSetup` to `simu.setup`
- [x] convert `simu.paraview` properties to structure, similar to morison element, note: test that sub-properties are tested 
    - `simu.dtParaview` to `simu.paraviewDt` to `simu.paraview.dt`
    - `simu.StartTimeParaview` to  `simu.paraviewStartTime` to  `simu.paraview.startTime`
    - `simu.EndTimeParaview` to `simu.paraviewEndTime` to `simu.paraview.endTime`
    - `simu.pathParaviewVideo` to `simu.paraviewDirectory` to `simu.paraview.path`
- [x] `simu.numWecBodies` to `simu.body.numHydroBodies`
- [x] `simu.pressureDis` to `simu.pressure`
- [x] `simu.simulationDate` to `simu.date`
- [x] add checks for simulationClass structures
- [x] `simu.adjMassWeightFun` to `simu.adjMassFactor`
- [x] `simu.autoRateTranBlk` to `simu.rateTransition`
- [x] `simu.zeroCrossCont` to `simu.zeroCross`
- [x] `simu.numIntMidTimeSteps` removed
- [x] `parallelComputing_dir` to `pctDir` **NOTE** this is not in the simulationClass, but maybe it should be

**Body Class**
- [x] `body.dof_start` to ``body.dofStart``
- [x] `body.dof_end` to ``body.dofEnd``
- [x] `body.dof_gbm` to ``body.dofGBM`` to `body.gbmDOF`
- [x] `body.nlHydro` to ``body.nonlinearHydro``
- [x] `body.lenJ` to ``body.dofCoupled``
- [x] `body.meanDriftForce` to ``body.meanDrift``
- [x] `body.bodyparaview` to ``body.paraviewBody`` to ``body.paraview``
- [x] `body.flexHydroBody` to ``body.flexBody`` to ``body.flex``
- [x] `body.nhBody` to ``body.nonHydroBody`` to ``body.nonHydro``
- [x] `body.hydroDataBodyNum` to ``body.hydroBodyTotal`` to `body.hydroTotal` **NOTE** Do we even use this?
- [x] `body.viscDrag` to `body.viscousDrag` to `body.quadDrag`
- [x] `body.userDefinedExcIRF` to `body.excitationIRF`
- [x] add checks for bodyClass structures
- [x] move `simu.yaw` and `simu.yawThresh` to bodyClass 
   - [x] `simu.yaw` to `body.yaw.option`
   - [x] `simu.yawThres` to `body.yaw.threshold`
- [x] `body.bodyNumber` to `body.number`
- [x] `body.bodyTotal` to `body.total`
- [x] `body.bodyGeometry` to `body.geometry`

**Cable Class**
- [x] `cable.c` to `cable.damping`
- [x] `cable.k` to `cable.stiffness`
- [x] `cable.viscDrag` to `cable.viscousDrag` to `cable.quadDrag` 
- [x] `cable.cableNum` to `cable.number`
- [x] `cable.loc` to `cable.location`

**Constraint Class**
- [x] `constraint.loc` to `constraint.location`
- [x] `constraint.constraintNum` to `constraint.number`

**PTO Class**
- [x] `pto.loc` to `pto.location`
- [x] `pto.c` to `pto.damping`
- [x] `pto.k` to `pto.stiffness`
- [x] `pto.ptoNum` to `pto.number`

**Mooring Class**
- [x] `mooring.ref` to `mooring.loc` to `mooring.location`
- [x] `mooring.loc` to `mooring.orientation` (internal)
- [x] `mooring.mooringNum` to `mooring.number`

**Doc**
- [ ] add dev documentation for style guide, look into naming convention, e.g. pep 8

**Notes**
- [x] Are the property structure fields checked? No, properties are automatically checked, but not the structure fields. For example there's an error if `waves.bems` is specified in the input file, but not for `waves.bem.options`. This can be addressed by adding some additional checks to the `checkinputs` method of each class with a structure.
- [ ] how does b2b impact migration of passive yaw to bodyClass?
- [ ] resolve `TestPassiveYawRegression` test failure
- [ ] resolve `wecSimPCT` issue
- [ ] move `pctDir` to simulationClass?

### CODE REVIEW

**Comment by kmruehl** [comment]
@akeeste and @nathanmtom I am actively working on this PR to resolve some of the bugs related to the applications tests, refer to https://github.com/WEC-Sim/WEC-Sim_Applications/pull/17, but it's ready for your review.

**Comment by kmruehl** [comment]
Thanks @akeeste for https://github.com/WEC-Sim/WEC-Sim/pull/822/commits/3adb4a1a2406b372f9ab89d3eb721891f9af1ab7

**Comment by kmruehl** [comment]
@nathanmtom thanks, I'll work on incorporating those revisions now

**Comment by nathanmtom** [comment]
@kmruehl Apologies for my slow review, going through the rest of the PR this afternoon. I'll update in the comment above with any other potential changes. Let me know if there is anything you want to discuss on any of my comments/suggestions.

**Comment by kmruehl** [comment]
@nathanmtom thanks! I'll work on the ones that we're 100% on, and wait for the team meeting to discuss the rest.

**Comment by kmruehl** [comment]
@WEC-Sim/wec-sim-lab-team  I'm going to merge this PR into dev and re-open a new one to resolve the remaining issues

**Pull request merged**
