### PR TITLE
Full dir spectra (resolved conflicts)

### PR DESCRIPTION
**Pull request by jtgrasb**
This PR is a for #1328 and attempts to resolve the merge conflicts.

### CODE REVIEW

**Comment by dforbush2** [comment]
Sorry Jeff. Lets talk to Adam and see what changes were made. we may be able to add them to this PR. Apologies I didn't realize this was waiting on me for a merge.

**Comment by jtgrasb** [comment]
No problem. I thought I had left a comment for you to review it, but I guess I didn't

**Comment by jtgrasb** [comment]
To do:
1. Pull in latest dev branch and resolve conflicts, using body elements library from dev.
2. Re-add full directional spectrum variant subsystem to the body elements library.
3. Test full directional spectrum functionality and edit PR if necessary.

**Comment by dforbush2** [comment]
@jtgrasb you can use the input data 'fullDirWave.mat' I have sent via email. These are (frequency, amplitude, direction, spread) as specified. You will need an input file with 
 waves = waveClass('spectrumImportFullDir');     
waves.spectrumFile = ('fullWaveDir.mat'); 
waves.freqDepDirection.directions = fullDirWave(:,3);
waves.freqDepDirection.spreads = fullDirWave(:,4);
waves.freqDepDirection.dirRes =10 ; % for example
waves.freqDepDirection.nbins=10; % for example
waves.freqDepDirection.spreadRange=2; % for example

I recommend the Pioneer as a test case.

**Comment by jtgrasb** [comment]
Thanks @dforbush2. I tried the full directional spectrum with the pioneer example and I am getting this error. Will work on resolving this week if I have some time. 
image

Here's a zip for the test case: [pioneerTest.zip](https://github.com/user-attachments/files/17936717/pioneerTest.zip)

**Comment by dforbush2** [comment]
@jtgrasb this is good to go! HOWEVER: at this time it will not work with non-linear hydro. That will require another variant subsystem and library change, and I think is best reserved for a future PR.

**Comment by jtgrasb** [comment]
This looks great and functionality seems to work well! A few questions/suggestions:
1. Looks like this doesn't work with wave markers either. Is that intentional? Since spectrum import works with the wave markers, we should be able to get this working with wave markers, right?
2. Can you add the Simulink variant variables (e.g. sv_fullDirIrregularWaves_b*) to the clear line in stopWecSim?

**Comment by dforbush2** [comment]
Can you please post the error You are seeing when run with wave markers? I believe I fixed that…And local testing it does work. I can add the necessary clear statement to stopWecSim. Thank you for the reminder.
________________________________
From: jtgrasb ***@***.***>
Sent: Tuesday, December 10, 2024 8:33:05 AM
To: WEC-Sim/WEC-Sim ***@***.***>
Cc: Forbush, Dominic Dean ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [WEC-Sim/WEC-Sim] Full dir spectra (resolved conflicts) (PR #1332)


This looks great and functionality seems to work well! A few questions/suggestions:

  1.  Looks like this doesn't work with wave markers either. Is that intentional? Since spectrum import works with the wave markers, we should be able to get this working with wave markers, right?
  2.  Can you add the Simulink variant variables (e.g. sv_fullDirIrregularWaves_b*) to the clear line in stopWecSim?

**Comment by jtgrasb** [comment]
It doesn't produce an error, it just doesn't plot the wave markers. There's a line in initializeWecSim where the visualization is only on if typeNum is less than 30:
image

**Comment by dforbush2** [comment]
Thanks good catch. That logic statement should also include the new typeNum which I think is 35.

You can also make these changes if you want, let me know.
________________________________
From: jtgrasb ***@***.***>
Sent: Tuesday, December 10, 2024 9:07:51 AM
To: WEC-Sim/WEC-Sim ***@***.***>
Cc: Forbush, Dominic Dean ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [WEC-Sim/WEC-Sim] Full dir spectra (resolved conflicts) (PR #1332)


It doesn't produce an error, it just doesn't plot the wave markers. There's a line in initializeWecSim where the visualization is only on if typeNum is less than 30:
image.png (view on web)<https://github.com/user-attachments/assets/0da02f49-66f6-45f4-b1c1-0ce49d1effe0>

**Comment by dforbush2** [comment]
@jtgrasb tested on pioneer  and everything works. This is ready to merge.

**Pull request merged**
