### PR TITLE
AQWA Examples

### PR DESCRIPTION
**Pull request by jtgrasb**
This PR adds Ansys AQWA example cases to be consistent with the example cases for WAMIT/NEMOH/Capytaine.

### CODE REVIEW

**Comment by kmruehl** [comment]
@jtgrasb refer to https://github.com/WEC-Sim/WEC-Sim/pull/761#issuecomment-988172945. Can you look into the IRR issue and compare the AQWA solutions to the other BEM data, e.g. WAMIT? Also, it looks like the tests are failing due to a directory issue (RM3data versus RM3)

**Comment by jtgrasb** [comment]
@kmruehl Thanks for fixing the RM3data issue -- I should've tested that locally first, whoops. I will work on addressing the RM3 issue.

**Comment by kmruehl** [comment]
@jtgrasb I made the same mistake of forgetting to run the tests locally on the master branch, no worries, it happens :)

**Comment by jtgrasb** [comment]
I made improvements to the RM3 example based on the examples in the shared drive. I am still getting instabilities in the radiation damping and the added mass plots. I even tried running the examples on the shared drive and got similar instabilities.
rad
add

**Comment by kmruehl** [comment]
@jtgrasb thank you so much, this looks great! I compared the RM3 results between AQWA and WAMIT, and they have very good agreement for Heave, but agreement is not so great in Surge/Pitch. So the good news is the frequency spike around 2 rad/s for the AQWA RM3 results is not affecting the primary (power take-off) DOF. Overall these results are much improved and we should go ahead and merge them. 

I also compared:

- Coe_comp results between AQWA and WAMIT, they have good agreement in all 3 DOFs.
- Cubes results between AQWA and WAMIT, they have good agreement in all 3 DOFs.
- Cylinder results between AQWA and WAMIT, they have good agreement in all 3 DOFs.
- Ellipsoid results between AQWA and WAMIT, they have good agreement in all 3 DOFs. But the AQWA results at higher frequencies aren't very smooth. Was this case run with equal period spacing? If so, please run it with equal frequency spacing. 
- OSWEC results between AQWA and WAMIT, they have good agreement in all 3 DOFs.
- Sphere results between AQWA and WAMIT, not very many frequencies for the AQWA run, this should be rerun.
- WEC3 results between AQWA and WAMIT, the AQWA results have a lot of spikes for low frequencies. This may be worth investigating.

**Comment by kmruehl** [comment]
@jtgrasb I'm going to go ahead and merge this PR so that we can add the AQWA examples into dev, thank you! Can you open a new PR to update the AQWA runs for the Ellipsoid, Sphere, and WEC3?

**Pull request merged**
