### PR TITLE
Update master to main

### PR DESCRIPTION
**Pull request by akeeste**
This PR addresses a few outstanding names changes described in #1215 on updating master to main.

It updates every reference to the master branch in our repo, except in ``release_notes.rst`` since the master branch was valid at the time of those releases.

Most of the lines changed come from correcting an old merge conflict in a LIS file

### CODE REVIEW

**Comment by akeeste** [comment]
@H0R5E we renamed our "master" branch to "main". Can you review this PR and 
- see if there's anything else needed to get Actions up and running on the main branch again
- I believe these changes will start building our documentation at https://wec-sim.github.io/WEC-Sim/main/index.html instead of https://wec-sim.github.io/WEC-Sim/main/index.html. Can you confirm? And if so, is there any way we can get our old docs to redirect to the new URL?

**Comment by H0R5E** [comment]
@akeeste, as I said in Applications, you might want to consider renaming `run-tests-master.yml` to `run-tests-main.yml` and then updating the README.

To redirect the docs, you're going to have to change [this line](https://github.com/WEC-Sim/WEC-Sim/blob/5e65f1f54c05a9656d1e5b15a1ca116833d1062c/docs/_assets/gh-pages-redirect.html#L6) so that the `url` field is now `url=./main/index.html"`.

**Review by H0R5E — CHANGES_REQUESTED** [review]
See previous comments.

**Comment by H0R5E** [comment]
@akeeste you will also need to update [this line](https://github.com/WEC-Sim/WEC-Sim/blob/5e65f1f54c05a9656d1e5b15a1ca116833d1062c/docs/conf.py#L76) to reference main rather than master. I only just remembered, sorry.

**Comment by H0R5E** [comment]
@akeeste, I've added https://github.com/akeeste/WEC-Sim/pull/13 which makes the change I suggested above and also adds a second redirect from `/master/index.html` to `/main/index.html`. This should mean that any only links that went straight to `master` instead of the root index will be redirected.

**Comment by H0R5E** [comment]
One last comment, Adam, is that you will need to sync the `dev` branch after merging this, otherwise it's docs builds won't create the `main` branch version.

**Comment by akeeste** [comment]
Thanks for your help @H0R5E! Once this is merged, I'll pull this and a few other bugfixes from master into dev.

Since the docs will now redirect, I finished changing every reference to the old docs here and on WEC-Sim/WEC-Sim_Applications#59. The test to build the current branch docs is failing because it's trying to reference the main branch on the Applications repo, which does not exist yet. It will pass once the WEC-Sim_Applications branch name is renamed.

Unfortunately from the labs, only @kmruehl has access to the Applications repo to rename master to main, and is unable to for two more weeks. @H0R5E do you have access [here](https://github.com/WEC-Sim/WEC-Sim_Applications/settings) to do this?

**Comment by H0R5E** [comment]
@akeeste, sorry for the delay in replying. I'll add a main branch to the repo now and we can check it's working OK, prior to changing the default.

**Comment by akeeste** [comment]
I've only found one more reference to the master branch documentation. It's a comment within the WECSim_Lib_PTOSim.slx but I can't find it for the life of me. I suggest we let that go for now since it should redirect anyways, and it's very unlikely to be used or found by anyone

**Review by H0R5E — APPROVED** [review]

**Comment by H0R5E** [comment]
> I suggest we let that go for now since it should redirect anyways, and it's very unlikely to be used or found by anyone

@akeeste, agreed. We can tidy up any little things in the future, and this is important to get merged ASAP. Thanks for the great work.

**Comment by H0R5E** [comment]
@akeeste, I've applied this to the `dev` branch in #1240, FYI.

**Comment by kmruehl** [comment]
@akeeste and @H0R5E thank you both for resolving these issues while I was OOO

**Pull request merged**
