### PR TITLE
Updates to the morisonElement and nlHydro Implementation

### PR DESCRIPTION
**Pull request by nathanmtom**
Originally WEC-Sim would activate the morisonElement and nlHydro as a global variable across all bodies. This update allows the user to select individual bodies and activate the morisonElement or nlHydro options for that body. This should help improve computational time for bodies that do not have active elements. 

To Do:
- [x] Update WEC-Sim_Applications wecSimInputFile.m to reflect changes implemented in this pull request. All tests past except for MoorDyn and Paraview applications since I do not have this installed on my machine.
- [x] Verify updates did not influence functionality with running WEC-Sim from Simulink. akeeste has volunteered to review changes to the mask initialization files.

### CODE REVIEW

**Comment by nathanmtom** [comment]
@akeeste I was hoping you could check if I edited the `run from Simulink` files correctly with this pull request. I made some edits that let the checks pass; however, I am not sure if I broke other functionality in the mask. The issue I ran into was the mask initialization looking for the `simu.morisonElement` option which has now been transferred to `body(ii).morisonElement.option`. Hopefully, this helps narrow down the edits I made and which files to check. I believe you have the most experience with that functionality, if I'm mistaken please tag the right team member. Thanks in advance!

**Comment by akeeste** [comment]
@nathanmtom Yes I can check the masks and callbacks to ensure everything is working. I should get to it today or tomorrow.

**Review by akeeste — CHANGES_REQUESTED** [review]
@nathanmtom 
Can you grant me push access to your repo? I have a few updates to make the Run from Simulink feature work robustly. Otherwise I can put a PR into your branch from mine.

**Comment by nathanmtom** [comment]
@akeeste Thanks for the review, I believe I have opened editing permission to my repo. If you still are having issues, then the pull request option would be fine.

**Comment by akeeste** [comment]
@nathanmtom Thanks! I was able to update your branch now. I added two commits that update the body mask callbacks to ensure the correct Morison Element parameters are visible depending on the chosen morisonElement.option and remove the old simu.morisonElement flag from the global reference frame.

Everything looks good on the Run From Simulink side of things!

Lastly, in a different PR I'm working on a developer manual addition about the callbacks and masks for Run From Simulink functionality. This will be aimed at helping the development team understand and change these features. I think you're the first to give it an attempt so if you have any feedback on what was difficult/confusing I'm happy to hear it.

**Review by akeeste — APPROVED** [review]

**Review by kmruehl — APPROVED** [review]
I've reviewed this as well, all tests on wec-sim and wec-sim_applications pass for me too. However we need to make a minor update to the WEC-Sim_Applications\Free_Decay\1m-ME example

**Comment by kmruehl** [comment]
@nathanmtom thank so much this is a huge improvement to the way WEC-Sim handles non-linear hydro and morison elements, thank you!

**Comment by nathanmtom** [comment]
@kmruehl I've just added you as a collaborator to my WEC-Sim Applications branch, but also if you let me know the update needed to be made happy to implement that since I thought I had double checked all application cases ran.

**Pull request merged**
