### PR TITLE
Converting WEC-Sim Library to referenced subsystems

### PR DESCRIPTION
**Pull request by kmruehl**
This PR builds on https://github.com/WEC-Sim/WEC-Sim/pull/667 with a different approach using [referenced subsystems](https://www.mathworks.com/help/simulink/ug/referenced-subsystem-1.html#responsive_offcanvas). 

Updates include:
- Split WEC-Sim Library into [sub-libraries](https://www.mathworks.com/help/simulink/ug/creating-block-libraries.html#brkngxr-3) for each class, e.g. Body, PTO, Constraint, Mooring, Frame
- Converted all linked library blocks into referenced subsystems, e.g. Non-Linear Hydro, B2B, Morison Element, etc
- Saved each referenced subsystem as light blue so they are easier to identify in the future
- Updated WEC-Sim library to R2020a to be consistent with WEC-Sim CI tests [MATLAB Build Status](https://github.com/WEC-Sim/WEC-Sim/actions/workflows/run-tests-master.yml)

To Do:
- [x] @yuyihsiang can you verify that I included all of the linked library blocks? 
- [x] @kmruehl look into accelerator and rapid-accelerator mode regarding, "Does not have code generation capability."
- [x] @kmruehl figure out why R2020a tests are failing, even though library is saved in R2020a and local tests are passing --> MATLAB bug in R2020a
- [x] @kmruehl  convert library class blocks to sub-library blocks and update forwarding table
- [ ] @kmruehl resolve issue with B2B subsystem

### CODE REVIEW

**Comment by yuyihsiang** [comment]
I got an error when running the library.

Error using wecSim (line 44)
Error evaluating 'StopFcn' callback of Frames block (mask) 'GBM/Global Reference Frame'.
Callback string is 'run('wecSimStopFunction')'
Caused by:
    Error using wecSim (line 44)
    wecSimStopFunction not found.
 
It seems that the 'wecSimStopFunction.m' does not exist in dev.

--Yi-Hsiang

**Comment by akeeste** [comment]
@kmruehl 
I have tried debugging this PR in R2020a, but I cannot find the issue. Whenever I run or save a model from Simulink, MATLAB crashes. All the error message relate to internal Simulink issues that I cannot debug easily. I can keep looking at this, but am a bit stuck on how to go about this.

Also, I completed a preliminary study on how the referenced subsystems affect the accelerator mode speed. I ran 30 OSWEC cases total (5 for each of the 3 modes in dev and this PR). The referenced subsystems seem to slow things down by approximately 20%.

Maybe it is worthwhile to switch back to the non-backwards compatible change using the Open Callback? Can we use the WECSim_Lib.slx/Library Properties/Forwarding Table to maintain backwards compatibility? It looks like this table has been used for changes in the past.

**Comment by kmruehl** [comment]
> 
> 
> I got an error when running the GBM case with the library.
> 
> Error using wecSim (line 44)
> Error evaluating 'StopFcn' callback of Frames block (mask) 'GBM/Global Reference Frame'.
> Callback string is 'run('wecSimStopFunction')'
> Caused by:
> Error using wecSim (line 44)
> wecSimStopFunction not found.
> 
> It seems that the 'wecSimStopFunction.m' does not exist in dev.
> 
> --Yi-Hsiang

@yuyihsiang this issue should be resolved with 29f2af6d2c2a6662b09d0d4fab51e3e1ace90cf4 can you try GBM again?

**Comment by kmruehl** [comment]
@akeeste I've also been trying to debug the referenced subsystems issues in 2020a with no luck. It looks like there is a known [bug that was resolved in 2020b](https://blogs.mathworks.com/simulink/2019/11/15/new-in-r2019b-subsystem-reference/). The referenced subsystem feature was added in 2019b but not fully functional until 2020b.

**Comment by kmruehl** [comment]
> Also, I completed a preliminary study on how the referenced subsystems affect the accelerator mode speed. I ran 30 OSWEC cases total (5 for each of the 3 modes in dev and this PR). The referenced subsystems seem to slow things down by approximately 20%.

Good to know, thanks for looking into this. 

> Maybe it is worthwhile to switch back to the non-backwards compatible change using the Open Callback? Can we use the WECSim_Lib.slx/Library Properties/Forwarding Table to maintain backwards compatibility? It looks like this table has been used for changes in the past.

I'll look into implementing this, but the sub-libraries did not fully resolve the library issues because they cannot be used for the linked library blocks between Rigid Bodies (Hydro, Non-Hydro and Drag) and Flex body:
- Additional_Linear_Damping_Force_Calculation.slx
- B2B_Subsystem.slx
- Morison_Element_and_Viscous_Damping_Force_Calculation.slx
- Net_Buoyancy_Force.slx
- Nonlinear_Wave_Elevation.slx
- Wave_Radiation_Forces_Calculation.slx
I think the solution will have to be a combination of sub-libraries and referenced libraries, which hopefully will not reduce speed by 20%, but TBD

**Comment by kmruehl** [comment]
@akeeste  and @yuyihsiang this is ready for another review. Also, all tests are passing, even R2020a: https://github.com/WEC-Sim/WEC-Sim/pull/688/checks

**Comment by kmruehl** [comment]
WEC-Sim tests are passing, but the WEC-Sim_Applications B2B tests fail

```matlab
 Failed to evaluate mask initialization commands.
        Error using wecSim (line 44)
        Block 'RM3/Spar//Plate/Hydrodynamic Body/B2B Subsystem/B2B Subsystem/B2B/CrossCoupling'
        is inside a Subsystem Reference block 'RM3/Spar//Plate/Hydrodynamic Body/B2B Subsystem'.
        Incorrect to modify contents of a Subsystem Reference block using callback code.
```

**Review by akeeste — CHANGES_REQUESTED** [review]
@kmruehl I think this is a great improvement to our workflow and will be very helpful in merging many library PRs at once. I'm glad you found a way to make it backwards compatible; that was my main concern with the previous method.

My only suggestion is to add a few more Referenced subsystems for items that can be linked together:
- Create ``Structure`` or ``Motion Sensor`` subsystem to replace the following:
    - ``WECSim_Lib_Body/Rigid Body/Hydrodynamic Body/Structure``
    - ``WECSim_Lib_Body/Rigid Body/Non-Hydro Body/Structure``
    - ``WECSim_Lib_Body/Flex Body/Structure``
- Create ``Wave Diffraction and Excitation Force Calculation`` subsystem to replace the following:
    - ``WECSim_Lib_Body/Rigid Body/Hydrodynamic Body/Wave Diffraction and Excitation Force Calculation``
    - ``WECSim_Lib_Body/Flex Body/Wave Diffraction and Excitation Force Calculation``
- Add ``Net_Buoyancy_Force`` subsystem to replace:
    - ``WECSim_Lib_Body/Flex Body/Hydrostatic Restoring Force Calculation/Hydrostatic Restoring Force Calculation/Linear and Nonlinear Restoring Force Variant Subsystem/Linear Hydrostatic Restoring Force /Net Buoyancy Force``

I think these three items will cover any old links and prevent code duplication in the library.

**Comment by kmruehl** [comment]
This PR is partially covered by https://github.com/WEC-Sim/WEC-Sim/pull/712 to include sub-libraries for the following blocks:
- cables
- ptos
- constraints

**Comment by kmruehl** [comment]
This PR is partially covered by https://github.com/WEC-Sim/WEC-Sim/pull/714 to include sub-library for the following block:
- frames

**Pull request closed without merging**
