### PR TITLE
Fix AQWA data for sphere, ellipsoid, and WEC3

### PR DESCRIPTION
**Pull request by jtgrasb**
This PR addresses comments from https://github.com/WEC-Sim/WEC-Sim/pull/779

### CODE REVIEW

**Comment by kmruehl** [comment]
This PR updates the AQWA runs for the following cases:
- [ ] Ellipsoid
- [ ] Sphere
- [ ] WEC3

**Review by kmruehl — CHANGES_REQUESTED** [review]
Refer to comments about Sphere and WEC3

**Comment by jtgrasb** [comment]
Thanks for the input @kmruehl. I was looking mostly at the shapes rather than values so didn't really notice the differences with the sphere (I guess that's why we need the compareBEM function haha) -- thanks for pointing those out. I will try a few things and should be able to figure it out. As for the WEC3, I'm not quite sure what the issue may be, but I'll try adjusting the mesh a bit and see how that changes it.

**Comment by kmruehl** [comment]
Thanks! And hopefully the updates to plotBEMIO will make this comparison much easier :)

**Comment by kmruehl** [comment]
@jtgrasb I found another run that needs to be updated, the RM3, especially the radiation damping. There is a frequency spike around 2 rad/s that's making the IRF unstable, especially in surge and pitch. This plot is comparing the WAMIT to the AQWA solution for the RM3.

image
image

**Comment by kmruehl** [comment]
@jtgrasb https://github.com/WEC-Sim/WEC-Sim/pull/790 has been merged into dev, so please pull this into this PR

**Comment by jtgrasb** [comment]
@kmruehl Okay, I've pulled the CompareBEMIO updates into this PR and I will check out the RM3 as well. Thanks!

**Comment by kmruehl** [comment]
Great, thank you!

**Comment by jtgrasb** [comment]
I have fixed the example cases for the sphere and ellipsoid and also improved the example case for the RM3. Unfortunately, the RM3 and WEC3 still have unstable IRF's in surge and pitch that I am working on fixing.

**Comment by akeeste** [comment]
@jtgrasb Have you tried changing the frequency limit for the IRF? If you can't get rid of the IRR problems in Aqwa itself, you can adjust this limit to try and tune the IRF. Not sure what you're using now, but if you set the frequency limit in the IRF to 2rad/s then most IRR spikes are avoided and the IRF may decay better. This worked somewhat in OMT, might be useful here.

**Comment by kmruehl** [comment]
@jtgrasb is this ready for a review?

**Comment by jtgrasb** [comment]
Although the WAMIT results seem to avoid the spikes for the RM3, the Capytaine and Nemoh results have similar spikes and just use a frequency limit for the IRF. I will keep looking into potential solutions for the RM3 and WEC3, but I think it is okay to merge for v5.0 for now.

**Review by kmruehl — APPROVED** [review]
Thanks @jtgrasb I'm merging this now

**Pull request merged**
