### PR TITLE
PTO Extension Feature

### PR DESCRIPTION
**Pull request by Allison-File**
The PTO Extension feature was developed to address the issues described within the ‘new initial displacement implementation’ task card. The current initial displacement feature doesn't actually displace bodies but instead changes their locations entirely. The PTO Extension feature corrects this issue by allowing for the defined PTO displacement to propagate throughout the system, resulting in an accurate reflection of the initial position of each body without requiring the user to individually calculate and define. This feature was implemented on several PTO library blocks including: Translational PTO, Rotational PTO, Rotational PTO Actuation Motion, and Translational PTO Actuation Force.

The PTO Extension Feature includes the following changes:

1. Established an ‘extension’ property within the PTO Class
        -This property defines the priority, value, and checkbox initialization options for the specify position target checkbox of 
           each PTO library block joint

2. Edited the PTO library blocks
        - Set the joint block position target value as pto.extension.PositionTargetValue, which can be defined in the 
           wecSimInputFile

        - Added an if statement in the PTO library block mask to allow the pto.extension.PositionTargetSpecify to 
          turn on the specify position target checkbox if defined as a value of 1 in the wecSimInputFile.

3. Documentation
        - Updated the pto.rst file to include a detailed explanation of the PTO Extension Feature and how to initialize within the 
         wecSimInputFile. This includes a visual of the feature being implemented within the WECCCOMP wavestar model.

        - Updated the applications.rst file to include an explanation of the applications case employing the PTO Extension 
         feature for the RM3 model.

[PTO Extension Feature.pdf](https://github.com/WEC-Sim/WEC-Sim_Applications/files/13892141/PTO.Extension.Feature.pdf)

### CODE REVIEW

**Comment by Allison-File** [comment]
[PTO Extension Feature.pdf](https://github.com/WEC-Sim/WEC-Sim/files/13892035/PTO.Extension.Feature.pdf)

This paper provides further documentation of the PTO Extension Feature, including the development process and simulation results.

**Comment by akeeste** [comment]
Hi @Allison-File Thanks for this PR. Can you give me write access to your WEC-Sim fork so that I can push some minor updates before we merge this PR? I should be able to push just to this branch, but for some reason GitHub is not allowing it.

**Comment by Allison-File** [comment]
Hi @akeeste I just sent you a collaborator invite for my repository. Please let me know if you need anything else from my end.

**Comment by akeeste** [comment]
@Allison-File Great, thank you! That should be all I need

**Review by akeeste — APPROVED** [review]
Thanks @Allison-File for all of your work on this PR and apologies for the delay in merging it. In reviewing I made a few changes:
- added to documentation updates
- applied the extension feature to constraints as well

As a general note for our development team, we are inconsistent in angular units are input to WEC-Sim. We should be aware of this and possibly rectify it later on:
degrees: wave heading, pto/constraint hard stops limits, pto/constraint extension
radians: body/constraint/pto setInitDisp functions,  body.initial.angle

**Pull request merged**
