### PR TITLE
Update Capytaine wrapper for parallel simulation

### PR DESCRIPTION
**Pull request by akeeste**
This is a copy of PR #635 with the fixes for the freeze_support error and the meshmagick bug.
Copying old PR to get updates in more quickly.

### CODE REVIEW

**Comment by akeeste** [comment]
@dav-og Any more comments before merging this? It is identical to Yi-Hsiang's branch in #635 but with my changes that I had trouble pushing there.

**Comment by akeeste** [comment]
Checked this PR one final time. Things are working for me on Windows. Parallelization appears to be working properly and increases the number of cores used.

**Comment by dav-og** [comment]
> 
> 
> Checked this PR one final time. Things are working for me on Windows. Parallelization appears to be working properly and increases the number of cores used.

I reduced # of frequencies, ran into an error - working through it...

**Comment by dav-og** [comment]
@akeeste @yuyihsiang
just added encoding args to .to_netcdf() call

**Comment by akeeste** [comment]
> just added encoding args to .to_netcdf() call

Thanks @dav-og! Confirmation this update still works with my version of xarray (v0.16.1)

**Pull request merged**
