### PR TITLE
readCapytaine - get Khs from .nc files when bodies have less than 6 DOFs

### PR DESCRIPTION
**Pull request by akeeste**
This PR adds onto #1263 and allows ``readCapytaine`` to process hydrostatic stiffness (Khs) from the .nc file when there are multiple bodies with <6 DOFs.

Testing this depends on the bugfix in #1274 and should be merged after that PR.

### CODE REVIEW

**Comment by kmruehl** [comment]
@akeeste how do you recommend testing this feature?

**Comment by akeeste** [comment]
> @akeeste how do you recommend testing this feature?

We were using a TEAMER case internally. I'll upload a simple sample case

**Comment by akeeste** [comment]
@kmruehl In running a couple test cases and edge cases, I ran into an issue. I'll work through it and let you know when the fix is pushed

**Comment by akeeste** [comment]
@jleonqu I think I fixed the bug in this PR. I attached a zip of several edges cases to test against.

[readCapytaine_Khs_cases.zip](https://github.com/user-attachments/files/16899567/readCapytaine_Khs_cases.zip)

**Review by jleonqu — APPROVED** [review]
I reviewed this PR and I didn't have any issues. I run all the tests locally and I used the cases provided by @akeeste with no issues. This is ready to merge.

**Comment by akeeste** [comment]
Thanks @jleonqu!

**Comment by kmruehl** [comment]
Thanks @jleonqu

**Pull request merged**
