### PR TITLE
New Documentation Structure

### PR DESCRIPTION
**Pull request by akeeste**
This PR contains updates to the new documentation discussed in issue #455. This includes:
- separating the current documentation into 3 manuals: user, theory, development
- Creates a new introduction/overview section of WEC-Sim on the landing page
- restructures the 'Code Structure' section

When approved, the docs directory can be replaced with the docs_new directory to update the documentation fully.

### CODE REVIEW

**Comment by akeeste** [comment]
Currently, the new documentation is on a branch of @H0R5E's [fork](https://github.com/H0R5E/WEC-Sim/tree/new_docs_structure) and can be viewed [here](https://h0r5e.github.io/WEC-Sim/new/index.html).

**Comment by akeeste** [comment]
Hi @H0R5E 

I am currently changing this documentation structure to replace docs/ with docs_new/ so that it can merge into the dev branch and build in the previous manner. However WEC-Sim/dev includes some additional changes to the documentation. This is proving difficult to merge properly using git because the docs_new/*.rst files are reorganized and no longer tied to the docs/man/*.rst files. I have not found an easy way to combine changes from both branches.

Do you have any suggestions for merging this fork with any other docs updates on the WEC-Sim/dev branch? 

There are few enough documentation changes on dev that it should be possible to do manually, but I wanted to get your thoughts before going that route.

Adam

**Comment by H0R5E** [comment]
Hey Adam,

I think the closest thing to automation you can do is use a diff tool (like [Meld](https://meldmerge.org/), for instance) to merge the documents manually (assuming that the files being compared are similar). It would be a bit fiddly to do (you'd need a version of the repo prior to the creation of this branch to use as the base), but it might(?) help.

Alternatively, just note the changes in the `docs` folder since the docs_new branch was created (using a `git diff` or equivalent) and try to manually apply them in `docs_new`.

The file structure has been changed so much that automatic merge will have no chance of working, as you said. So, essentially, we need to manually merge and then overwrite the docs branch.

I have time to help with this if you want. Just let me know.

Mat

**Comment by akeeste** [comment]
Mat, 

Thanks for those suggestions. I'll take a try comparing the current dev docs with those when this branch split and inserting the changes into docs_new. I'll let you know if I could use assistance on this.

Adam

**Comment by nathanmtom** [comment]
@akeeste I'm just providing my vote that this PR be merged into Master and we get feedback from users, onboarding new employees, and our own use. I'm less concerned about the documentation structure and would like to personally find more time to make sure our documentation is up-to-date and accurate.

**Comment by akeeste** [comment]
@kmruehl @yuyihsiang 
I made the last few changes that were discussed on 5/21, and per Nathan's approved review, this PR should be ready to merge.

All concurrent changes to the dev docs have been pulled in. @H0R5E, thanks for your suggestions on this.

Adam

**Review by kmruehl — APPROVED** [review]
Looks good to me

**Comment by kmruehl** [comment]
@akeeste I just saw the comment from @nathanmtom about merging this directly into master. I like that idea. We can revert this merge and re-merge into master if you like that idea.

**Comment by H0R5E** [comment]
@akeeste, I've having a chat with @kmruehl right now, so we'll discuss getting it compiling again.

**Comment by kmruehl** [comment]
@akeeste thanks for lettings us know. @H0R5E is looking into the issue now.

**Comment by H0R5E** [comment]
Fixed the build issue with 4737c71ae751bc05691056b53baf089216c6a182

**Pull request merged**
