### PR TITLE
Pull #1373 into dev

### PR DESCRIPTION
**Pull request by akeeste**
This is a draft PR to pull #1373 from main into dev. The merge will likely be done locally due to the difficulty of merging the slx files.

### CODE REVIEW

**Comment by akeeste** [comment]
@dforbush2 when doing this merge of the main library into dev using the matlab git mergetool, it did flag a change to the ``SimscapeInstrumentationLogging`` parameter within ``WECSim_Lib_Body_Elements/Rigid Body/Hydrodynamic Body/Structure/Body Properties``. The main branch had this parameter disabled, while the dev branch had it enabled but off. I maintained the dev branch setting since it as not having the issue in #1381. Assuming the new dev branch does not have this issue, I think #1381 will be resolved when we force main to be dev during the release

**Comment by akeeste** [comment]
I have these changes complete locally (also on my fork's dev branch). All WEC-Sim repo tests pass on R2024a. Pushing changes now.

**Comment by jtgrasb** [comment]
@akeeste I don't see anything you missed at first glance, but I can take a deeper look tomorrow. As for the `SimscapeInstrumentationLogging` parameter, where do you see this in body properties? I can't seem to find it.

**Comment by akeeste** [comment]
I don't see it either in the GUI. It first came up using the simulink compare tool. Maybe it's hidden or accessible via the command line view of the block parameters? Either way, I'm hoping #1381 does not reappear. I didn't test with a broken library link yet. 

Also since I had to push directly to merge the PR, we should just make any other modifications needed in another PR into dev

**Pull request merged**
