### PR TITLE
Make mooringClass.moorDynInput case insensitive

### PR DESCRIPTION
**Pull request by H0R5E**
This PR makes the `mooringClass.moorDynInput` method insensitive to the case of folders and files required by MoorDyn.

Currently, MoorDyn requires that the `Mooring` folder (which contains the `lines.txt` file) should have a capital Em as shown by [this line](https://github.com/mattEhall/MoorDyn/blob/ea5ccf8c050f359cdd13a0a8b6f5cc5f3158405c/MoorDyn.cpp#L287) in the [MoorDyn](https://github.com/mattEhall/MoorDyn) source code. Because Linux is case sensitive, changing the folder name to have a capital em brakes the `moorDynInput` method of the `mooringClass` class and, therefore, this change is required for the [WEC-Sim_Applications](https://github.com/WEC-Sim/WEC-Sim_Applications) tests to run correctly on GitHub Actions.

This PR makes the following changes:

* Add `caseInsenstiveDir` function to match file objects regardless of case.
* Changes `mooringClass.moorDynInput` to use `caseInsenstiveDir` to locate the `Mooring` folder and `lines.txt`.
* Add tests of both `caseInsenstiveDir` and `mooringClass.moorDynInput` in new `objects` and `functions` sub-directories of the `tests` directory.
* Fixes bad line endings (`^M`) in the `mooringClass.m` file

### CODE REVIEW

**Comment by akeeste** [comment]
@H0R5E The linked test result doesn't show an error with MoorDyn that I can see, but I don't see an issue with updating this to match MoorDyn's syntax. I can confirm the MoorDyn application works for me on Windows with the folder name capitalized.

**Comment by H0R5E** [comment]
Hi @akeeste, sorry my explanation was a bit brief. The problem occurs on Linux, because Linux uses case sensitive file names. For the [Moordyn application example](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/Mooring/MoorDyn), MoorDyn does not like that the `mooring` folder is not capitalized, resulting in:

```
Running MoorDyn (v1.01.03C, 2021-03-09)
     Copyright (c) Matt Hall and NREL, licensed under GPL v3.
  Error: unable to open lines.txt file
```

which breaks the test case. Renaming this folder to `Mooring` fixes MoorDyn, but then WEC-Sim complains:

```
  ================================================================================
  Error occurred in TestMooring/testMoorDyn and it did not run to completion.
      ---------
      Error ID:
      ---------
      'Simulink:Masking:Bad_Init_Commands'
      --------------
      Error Details:
      --------------
      Error using wecSim (line 45)
      Error in 'RM3MoorDyn/MoorDyn': Failed to evaluate mask initialization
      commands.
      
      Error in TestMooring/testMoorDyn (line 76)
                  wecSim
      
      Caused by:
          Error using wecSim (line 45)
          File not found.
  ================================================================================
```

So a fix needs added to WEC-Sim as well. This is probably related to issue #336 & #269. A more robust solution on the WEC-Sim side might be to read the file name in a case-insensitive manner, to avoid issues if MoorDyn changes again.

**Comment by H0R5E** [comment]
I'm trying something else with this.

**Comment by H0R5E** [comment]
Closing in favour of #682

**Pull request closed without merging**
