### PR TITLE
Update Read_AQWA

### PR DESCRIPTION
**Pull request by jtgrasb**
I altered the Read_AQWA function so that it can account for headers in the LIS file (resolves issue #683). AQWA places the headers in different places for the Froude-Krylov and Diffraction Forces depending on the amount of frequencies being run. The updated Read_AQWA function keeps a count of when a header is placed in order to skip the header and only read in the relevant data.

### CODE REVIEW

**Comment by jtgrasb** [comment]
I also updated the script to fix a bug that derives from my last PR for Read_AQWA. The added_mass was being overwritten with zeros the way I initially wrote the code so this commit fixes the added_mass readings.

**Comment by Devsh93** [comment]
Can you please upload updated github zip

**Comment by Devsh93** [comment]
Error using wecSim (line 46)
['RM3/Global Reference Frame/Solver Configuration']: Error evaluating equations at time
0.0045000000000000005. Stopping simulation.  There may be a singularity in the solution.  If not, try
reducing the step size (either by reducing the fixed step size or by tightening the error tolerances)
Caused by:
    Error using wecSim (line 46)
    ['RM3/Floating (3DOF)/CONSTRAINT (Planar Joint)']: 'RM3/Floating (3DOF)/CONSTRAINT (Planar Joint)' has a degenerate mass distribution on its follower side.

**Comment by jtgrasb** [comment]
@Devsh93 It seems like you had some issues with the RM3 AQWA example? I updated the AH1 and LIS files as I realized they weren't from my latest run -- thanks for catching it! For some reason, it won't let me upload a .zip file here, but let me know if you still need it and I can find a different way to upload.

**Comment by kmruehl** [comment]
@jtgrasb this PR resolves issues with the READ_AQWA script, so I'd like to merge that. However, the RM3 AQWA BEM solution for looks like it has an irregular frequency issue that's causing IRF instabilities. Have you compared this AQWA solution to the other RM3 runs? Did you run this case with an internal lid? 


image
image

**Comment by kmruehl** [comment]
@jtgrasb I'm going to merge this, but will reference this AQWA RM3 comment in another issue/pr

**Comment by kmruehl** [comment]
@jtgrasb would you like to delete this branch?

**Comment by jtgrasb** [comment]
@kmruehl Thanks! I deleted it and I will address the RM3 issue in the other PR.

**Pull request merged**
