### PR TITLE
Update OSWEC tutorial dimensioned geometry image

### PR DESCRIPTION
**Pull request by rakkarolina**
Current image for geometry in OSWEC tutorial seems underdefined. Created a new image that includes important dimensions the previous image seemed to lack in hopes that this makes the geometry easier to recreate. Checked these dimensions and CAD file from issue #496 to make sure they matched. 

Can make text larger or change orientations if needed.

### CODE REVIEW

**Comment by rakkarolina** [comment]
OSWEC_Geom
unsure if new image is able to be seen, commenting it here

**Comment by nathanmtom** [comment]
For comparison, I'm adding the current graphic found on the WEC-Sim Tutorials Oscillating Surge WEC (OSWEC) page: 

image

**Review by nathanmtom — APPROVED** [review]
The tutorial dimension image of the OSWEC has been improved and adds additional geometric description to help a new user recreate this example case.

**Review by dav-og — APPROVED** [review]

**Review by H0R5E — CHANGES_REQUESTED** [review]
This looks fine if the width of the image is increased in the docs. I increased the width to 600pt and it looked like this:

Capture

Maintainers can't edit this pull request, so I created a patch that should be applied to the docs:

```
From 0031e8727c636753b095c177e3f9ecb12ad90880 Mon Sep 17 00:00:00 2001
From: Mathew Topper <damm_horse@yahoo.co.uk>
Date: Thu, 8 Jul 2021 12:41:32 +0100
Subject: [PATCH] Increase image width to 600pt

---
 docs/user/tutorials.rst | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/user/tutorials.rst b/docs/user/tutorials.rst
index af896fe4..22a3297e 100644
--- a/docs/user/tutorials.rst
+++ b/docs/user/tutorials.rst
@@ -230,7 +230,7 @@ hinge to the base that restricts the flap in order to pitch about the hinge.
 The full-scale dimensions and mass properties of the OSWEC are shown below. 
 
 .. figure:: /_static/images/OSWEC_Geom.png
-   :width: 300pt
+   :width: 600pt
    :align: center
 
 +-------+---------------+
-- 
2.31.1.windows.1
```

If you save the above as a file called `my.patch` in the WEC-Sim root you can then run the following to apply the patch:

```
> cd \path\to\WEC-Sim
> git apply my.patch
```

It's just changing one line in the `docs/user/tutorials.rst` file (line 233), if you would prefer to do this manually.

**Comment by H0R5E** [comment]
I have resolved the merge conflict in #643. The change was made against an old version of the docs. Closing this and will merge the other.

@rakkarolina, thanks for your contribution.

**Pull request closed without merging**
